import { Router } from "express";
import usersRoute from "./users";
import superadminRoute from "./superadmin";
import adminRoute from "./admins";
import informationRoute from "./information";
const route = Router();
route.use("/superadmin", superadminRoute);
route.use("/users", usersRoute);
route.use("/admin", adminRoute);
route.use("/information", informationRoute);
export default route;
